#!/usr/bin/env bash

mili_celcius_temprature=$(grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | sed 's/label/input/' | cut -d':' -f1 | xargs cat)

# Following script outputs current cpu die temperature in milidegree-celcius, convert it to celcius and fahrenheit and display as:

# Celcius: 42.0 C
# Fahrenheit: 107.6 F


Celcius_temprature=$(echo "scale=1; $mili_celcius_temprature / 1000" | bc)
Fahrenheit_temprature=$(echo "scale=1; ($Celcius_temprature * 9/5) + 32" | bc)

echo "Celsius: $Celcius_temprature °C"
echo "Fahrenheit: $Fahrenheit_temprature °F"