#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format
#
# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md


# I added a for loop ,then use a conditional statement and by using both of them code will print permissions of the given files in octal format.

for file in "$@"; do

    if [ -e "$file" ]; then  

        permission=$(stat -c "%a" "$file" 2>/dev/null || stat -f "%A" "$file")  

        echo "$permission $file"

    else

        echo "Error: $file does not exist" >&2

    fi
done


