#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this

SSID=$(iw dev wlan0 link | grep 'SSID' | awk '{print substr($0, index($0,$2))}')


# I added a conditional Statement so that we can check whether the wifi is connected or not .

if [ -z "$SSID" ]; then

    echo "Currently wifi is not connected "

else

    echo " SSID (wifi username ) of connected wifi is : $SSID"

fi
